---
title: Setup Environment
description: >
  This task sets up the environment to RapidScripts, ensuring necessary tools are accessible.
actions:
  # Add RapidScripts folder to system path
  - !powerShell:
      command: '.\Setup-Environment.ps1'
      exeDir: true
      weight: 100