---
title: Xbox Game Bar
description: >
  The registry parameters disable the Xbox Game Bar feature. The Xbox Game Bar is a gaming overlay that lets you access various gaming features and actions,
  such as recording, streaming, chatting, and more.
actions:
  # Disable Game Bar Features
  - !registryValue:
      path: 'HKCU\System\GameConfigStore'
      value: 'GameDVR_Enabled'
      type: REG_DWORD
      data: '0'
  - !registryValue:
      path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\GameDVR'
      value: 'AppCaptureEnabled'
      type: REG_DWORD
      data: '0'

  # Disable Game Bar Tips and Start Panel
  - !registryValue:
      path: 'HKCU\Software\Microsoft\GameBar'
      value: 'GamePanelStartupTipIndex'
      data: '3'
      type: REG_DWORD
  - !registryValue:
      path: 'HKCU\Software\Microsoft\GameBar'
      value: 'ShowStartupPanel'
      type: REG_DWORD
      data: '0'
  - !registryValue:
      path: 'HKCU\Software\Microsoft\GameBar'
      value: 'UseNexusForGameBarEnabled'
      type: REG_DWORD
      data: '0'

  # Disable Game Bar Presence Writer
  - !registryValue:
      path: 'HKLM\SOFTWARE\Microsoft\WindowsRuntime\ActivatableClassId\Windows.Gaming.GameBar.PresenceServer.Internal.PresenceWriter'
      value: 'ActivationType'
      type: REG_DWORD
      data: '0'

  # Disable Game DVR and Broadcasting
  - !registryValue:
      path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\GameDVR'
      value: 'AllowGameDVR'
      type: REG_DWORD
      data: '0'
  - !registryValue:
      path: 'HKLM\SOFTWARE\Microsoft\PolicyManager\default\ApplicationManagement\AllowGameDVR'
      value: 'value'
      type: REG_DWORD
      data: '0'