---
title: Settings Page Visibility
description: >
  This section manages the visibility of settings pages depending on the Windows version.
actions:
  # Windows 10 Settings Pages
  - !cmd:
      exeDir: true
      command: 'RapidScripts\UtilityScripts\Set-Pages.cmd -addRapidWin10Def'
      builds: [ '<22000' ]

  # Windows 11 Settings Pages
  - !cmd:
      exeDir: true
      command: 'RapidScripts\UtilityScripts\Set-Pages.cmd -addRapidWin11Def'
      builds: [ '>=22000' ]