title: Configure Visual Settings
description: >
  This script configures various registry settings to adjust visual effects and system performance.
actions:
  # Configure registry settings to adjust visual effects and system performance
  - !powerShell:
      command: '.\MultiTool.ps1 -MyArgument set_visualeffects'
      runas: currentUserElevated
      exeDir: true
      weight: 100