---
title: Netsh Configuration
description: >
  The following commands configure various network-related settings on a Windows system using the netsh utility.
  Each command modifies specific parameter to enhance network performance.
actions:
  # Main internet settings
  - !run: {exe: 'netsh', args: 'int tcp set global initialRto=2000'}
  - !run: {exe: 'netsh', args: 'int tcp set global MaxSynRetransmissions=2'}
  - !run: {exe: 'netsh', args: 'int tcp set global pacingprofile=off'}
  - !run: {exe: 'netsh', args: 'int tcp set heuristics disabled'}
  - !run: {exe: 'netsh', args: 'interface Teredo set state type=enterpriseclient'}
  - !run: {exe: 'netsh', args: 'interface Teredo set state servername=default'}
  - !run: {exe: 'netsh', args: 'int tcp set supplemental internet congestionprovider=default'}

  # Newer Windows 11 builds introduced a bug that causes certain applications, notably CEF applications, to instantly crash or hang when using BBR2 congestion provider
  # https://sites.google.com/view/melodystweaks/windows-11-basic-optimizer?authuser=0
  - !run: {exe: 'netsh', args: 'int tcp set supplemental internet congestionprovider=cubic', builds: ['>=26100']}


  ### Deprecated

  # - !run: {exe: 'netsh', args: 'int tcp set global ecncapability=disabled'}
  # Reason: May reduce efficiency in managing network congestion.

  # - !run: {exe: 'netsh', args: 'int tcp set global timestamps=disabled'}
  # Reason: Disabling timestamps could disrupt packet timing.

  # - !run: {exe: 'netsh', args: 'int tcp set global hystart=disabled'}
  # Reason: May cause slower initial connection performance.

  # - !run: {exe: 'netsh', args: 'int tcp set global nonsackrttresiliency=disabled'}
  # Reason: Reduces RTT resilience on networks without SACK.

  # - !run: {exe: 'netsh', args: 'int tcp set security profiles=disabled'}
  # Reason: Weakens security measures against potential threats.