title: Windows Firewall Configuration
description: >
  This script enables/disables the Windows Firewall and its notifications.
actions:
  ## Disable all Firewall settings
  # Disable Windows Firewall and notifications for the Domain network profile
  - !registryValue:
      path: 'HKLM\SYSTEM\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\DomainProfile'
      value: 'EnableFirewall'
      type: REG_DWORD
      data: '0'
      option: 'disable-firewall'
  - !registryValue:
      path: 'HKLM\SYSTEM\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\DomainProfile'
      value: 'DisableNotifications'
      type: REG_DWORD
      data: '1'
      option: 'disable-firewall'

  # Disable Windows Firewall and notifications for the Private network profile
  - !registryValue:
      path: 'HKLM\SYSTEM\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\StandardProfile'
      value: 'EnableFirewall'
      type: REG_DWORD
      data: '0'
      option: 'disable-firewall'
  - !registryValue:
      path: 'HKLM\SYSTEM\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\StandardProfile'
      value: 'DisableNotifications'
      type: REG_DWORD
      data: '1'
      option: 'disable-firewall'

  # Disable Windows Firewall and notifications for the Public network profile
  - !registryValue:
      path: 'HKLM\SYSTEM\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\PublicProfile'
      value: 'EnableFirewall'
      type: REG_DWORD
      data: '0'
      option: 'disable-firewall'
  - !registryValue:
      path: 'HKLM\SYSTEM\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\PublicProfile'
      value: 'DisableNotifications'
      type: REG_DWORD
      data: '1'
      option: 'disable-firewall'