---
title: Configure Hosts to Block Telemetry
description: >
  This modification prevents microsoft telemetry from collecting and sending telemetry data using hosts, enhancing user privacy.
actions:
  # Disable hosts that potentially have telemetry
  - !powerShell:
      command: '.\Configure-DataCollection.ps1 -MyArgument disable_telemetry_with_hosts'
      exeDir: true
      weight: 100