---
title: Autologgers
description: >
  These configurations modify Windows Autologger settings, which control various system-level event logging mechanisms.
actions:
  - !powerShell:
      command: '.\MultiTool.ps1 -MyArgument configure_autologgers'
      exeDir: true
      wait: true
      weight: 100