---
title: Disable Windows Ads
description: >
  This file removes ads from settings and start menu, enhancing user experience and minimizing distractions.
actions:
  # A lot of features taken from here: https://www.elevenforum.com/t/disable-ads-in-windows-11.8004/

  # Turn off app suggestions in Start Menu
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager', value: 'SubscribedContent-338388Enabled', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager', value: 'SoftLandingEnabled', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\CloudContent', value: 'DisableSoftLanding', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'Start_IrisRecommendations', type: REG_DWORD, data: '0'} # "Recommendations for tips, shortcuts, new apps, and more"
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'Start_AccountNotifications', type: REG_DWORD, data: '0'} # "Microsoft account-related notifications"
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Explorer', value: 'HideRecommendedPersonalizedSites', type: REG_DWORD, data: '1'}
  - !registryKey: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager\SuggestedApps', operation: delete}

  # Remove advertisements from Settings app
  - !taskKill: {name: 'SystemSettings', ignoreErrors: true}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\WindowsRuntime\ActivatableClassId\ValueBanner.IdealStateFeatureControlProvider', value: 'ActivationType', type: REG_DWORD, data: '0', builds: [ '>=22000' ]} # Credits to @he3als
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer', value: 'AllowOnlineTips', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\PolicyManager\default\Settings\AllowOnlineTips', value: 'value', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager', value: 'SubscribedContent-338393Enabled', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager', value: 'SubscribedContent-353694Enabled', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager', value: 'SubscribedContent-353696Enabled', type: REG_DWORD, data: '0'}
  - !powerShell:
      command: '.\Disable-VelocityIDs.ps1'
      runas: currentUserElevated
      exeDir: true
      weight: 100
  - !appx: {name: '*Microsoft.Windows.ImmersiveControlPanel*', operation: clearCache}

  # Disable Lockscreen ads (Spotlight)
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager', value: 'SubscribedContent-338387Enabled', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager', value: 'RotatingLockScreenOverlayEnabled', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\CloudContent', value: 'DisableWindowsSpotlightFeatures', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\Software\Microsoft\Windows\CurrentVersion\Explorer\HideDesktopIcons\NewStartPanel', value: '{2cc5ca98-6485-489a-920e-b3e88a6ccce3}', type: REG_DWORD, data: '1'}

  # Disable 'Show me notifications in the Settings app'
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\SystemSettings\AccountNotifications', value: 'EnableAccountNotifications', type: REG_DWORD, data: '0'}

  # Disable Get tips and suggestions when using Windows
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager', value: 'SubscribedContent-338389Enabled', type: REG_DWORD, data: '0'}

  # Do not show me the Windows welcome experience after updates and occasionally when I sign in to highlight what's new and suggested
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager', value: 'SubscribedContent-310093Enabled', type: REG_DWORD, data: '0'}

  # Disable personalized recommendations
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\CloudContent', value: 'DisableWindowsConsumerFeatures', type: REG_DWORD, data: '1'}

  # Suggest ways to get the most out of Windows and finish setting up this device
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\UserProfileEngagement', value: 'ScoobeSystemSettingEnabled', type: REG_DWORD, data: '0'}

  # Disable Tailored experiences
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Privacy', value: 'TailoredExperiencesWithDiagnosticDataEnabled', type: REG_DWORD, data: '0'}

  # Disable "Include account-based insights, recent, favorite and recommended" for OneDrive in File Explorer
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Explorer', value: 'DisableGraphRecentItems', type: REG_DWORD, data: '1'}

  # Simple patch to the Windows hosts file, that causes the Outlook desktop client to stop displaying those annoying ads in your inbox (https://github.com/Pyenb/Outlook-desktop-ad-blocker)
  # - !powerShell: {command: 'Add-Content -Path "C:\Windows\System32\drivers\etc\hosts" -Value "0.0.0.0 m.adnxs.com"', runas: currentUserElevated} # AME Wizard stuterring with this method
  - !cmd: {command: 'findstr /c:"m.adnxs.com" %WinDir%\System32\drivers\etc\hosts >nul || echo 0.0.0.0 m.adnxs.com >> %WinDir%\System32\drivers\etc\hosts', runas: currentUserElevated}

  # Do not show me personalized ads by using my advertising ID
  - !task: {path: 'refinements\privacy\configure-advertising-id.yml'}