---
title: Clean Environment Paths
description: >
  This configuration cleans environment paths.
  It includes a PowerShell script for cleaning the environment paths and schedules
  this script to run every time the system starts.
actions:
  # Clean Environment Paths
  - !powerShell:
      command: '.\RapidScripts\UtilityScripts\Clean-EnvironmentPath.ps1'
      exeDir: true
      weight: 100

  # Schedule cleanup of environment paths to run at system startup
  - !run:
      exe: 'schtasks'
      args: '/create /tn "CleanEnvironmentPath" /tr "powershell.exe -ExecutionPolicy Bypass -File C:\Windows\RapidScripts\UtilityScripts\Clean-EnvironmentPath.ps1" /sc onstart /ru "NT AUTHORITY\SYSTEM" /f'
      runas: currentUserElevated