---
title: Disable Syncing
description: > 
  Disables syncing features by modifying registry settings and disabling related services.
actions:
  ## Disable Syncing
  # Turn off main sync mechanism
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\SettingSync', value: 'SyncPolicy', type: REG_DWORD, data: '5', option: 'disable-sync'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\SettingSync', value: 'DisableSettingSync', type: REG_DWORD, data: '2', option: 'disable-sync'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\SettingSync', value: 'DisableSettingSyncUserOverride', type: REG_DWORD, data: '1', option: 'disable-sync'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\SettingSync', value: 'DisableSyncOnPaidNetwork', type: REG_DWORD, data: '1', option: 'disable-sync'}
  # Turn off system applications sync
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\SettingSync', value: 'DisableApplicationSettingSync', type: REG_DWORD, data: '2', option: 'disable-sync'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\SettingSync', value: 'DisableApplicationSettingSyncUserOverride', type: REG_DWORD, data: '1', option: 'disable-sync'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\SettingSync', value: 'DisableAppSyncSettingSync', type: REG_DWORD, data: '2', option: 'disable-sync'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\SettingSync', value: 'DisableAppSyncSettingSyncUserOverride', type: REG_DWORD, data: '1', option: 'disable-sync'}
  # Turn off Credentials sync
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\SettingSync', value: 'DisableCredentialsSettingSync', type: REG_DWORD, data: '2', option: 'disable-sync'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\SettingSync', value: 'DisableCredentialsSettingSyncUserOverride', type: REG_DWORD, data: '2', option: 'disable-sync'}
  # Turn off Themes sync
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\SettingSync', value: 'DisableDesktopThemeSettingSync', type: REG_DWORD, data: '2', option: 'disable-sync'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\SettingSync', value: 'DisableDesktopThemeSettingSyncUserOverride', type: REG_DWORD, data: '1', option: 'disable-sync'}
  # Turn off Personalization sync
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\SettingSync', value: 'DisablePersonalizationSettingSync', type: REG_DWORD, data: '2', option: 'disable-sync'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\SettingSync', value: 'DisablePersonalizationSettingSyncUserOverride', type: REG_DWORD, data: '1', option: 'disable-sync'}
  # Turn off Start menu sync
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\SettingSync', value: 'DisableStartLayoutSettingSync', type: REG_DWORD, data: '2', option: 'disable-sync'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\SettingSync', value: 'DisableStartLayoutSettingSyncUserOverride', type: REG_DWORD, data: '1', option: 'disable-sync'}
  # Turn off Browser sync (Microsoft Edge)
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\SettingSync', value: 'DisableWebBrowserSettingSync', type: REG_DWORD, data: '2', option: 'disable-sync'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\SettingSync', value: 'DisableWebBrowserSettingSyncUserOverride', type: REG_DWORD, data: '1', option: 'disable-sync'}
  # Turn off sync in Settings
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\SettingSync\Groups\DesktopTheme', value: 'Enabled', type: REG_DWORD, data: '1', option: 'disable-sync'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\SettingSync\Groups\BrowserSettings', value: 'Enabled', type: REG_DWORD, data: '1', option: 'disable-sync'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\SettingSync\Groups\Credentials', value: 'Enabled', type: REG_DWORD, data: '0', option: 'disable-sync'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\SettingSync\Groups\Language', value: 'Enabled', type: REG_DWORD, data: '1', option: 'disable-sync'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\SettingSync\Groups\Accessibility', value: 'Enabled', type: REG_DWORD, data: '1', option: 'disable-sync'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\SettingSync\Groups\Windows', value: 'Enabled', type: REG_DWORD, data: '1', option: 'disable-sync'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\SettingSync\Groups\StartLayout', value: 'Enabled', type: REG_DWORD, data: '1', option: 'disable-sync'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\SettingSync', value: 'DisableWindowsSettingSync', type: REG_DWORD, data: '2', option: 'disable-sync'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\SettingSync', value: 'DisableWindowsSettingSyncUserOverride', type: REG_DWORD, data: '1', option: 'disable-sync'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\PolicyManager\default\Experience\AllowSyncMySettings', value: 'value', type: REG_DWORD, data: '0', option: 'disable-sync'}
  # Turn off Cloud Speech Recognition
  - !registryValue: {path: 'HKCU\Software\Microsoft\Speech_OneCore\Settings\OnlineSpeechPrivacy', value: 'HasAccepted', type: REG_DWORD, data: '0', option: 'disable-sync'}
  # Disable OneSync service
  - !service:
      name: 'OneSyncSvc'
      operation: change
      startup: 4
      option: 'disable-sync'