---
title: Windows Defender settings
description: >
  This execute file control over Windows Defender, a security feature providing antivirus and threat protection. 
  Enabling it enhances system security, while disabling it removes the protection, but increases performance.
actions: 
  - !writeStatus: {status: 'Disabling Windows Defender', option: 'disable-def'}
  - !powerShell:
      command: '.\Install-Software.ps1 -MyArgument install_defswitcher'
      runas: currentUserElevated
      exeDir: true
      weight: 100
      wait: true

  - !powerShell:
      command: '& "$env:WinDir\RapidScripts\UtilityScripts\DefenderSwitcher.exe" disable_av'
      option: 'disable-def'
      weight: 200
      wait: true