---
title: Security Configuration
description: >
  This modification configures multiple security-related settings in the system.
actions:
  # Run security configuration
  - !powerShell:
      command: '.\Security-Configuration.ps1'
      exeDir: true
      weight: 100