---
title: User Account Control
description: >
  UAC is a security feature that helps prevent unauthorized changes to the computer by asking for permission
  or an administrator password before allowing certain actions.
actions:
  - !writeStatus: {status: 'Configuring UAC'}

  ## RapidOS no longer disables UAC; users must report their actions.
   
  # Disable switching to the Secure Desktop when prompting for elevation
  - !registryValue:
      path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System'
      value: 'PromptOnSecureDesktop'
      type: REG_DWORD
      data: '0'