---
title: Configure Mitigations
description: >
  This PowerShell script is designed to modify registry settings
  for disabling or enabling mitigations against vulnerabilities.
actions:
  # Disable mitigations
  - !powerShell:
      command: '& "RapidScripts\UtilityScripts\Control-Mitigations.ps1" -MyArgument disable_mitigations'
      option: 'disable-mitigations'
      exeDir: true
      weight: 100 