---
title: Core Isolation Configuration
description: >
  These commands control Windows Virtualization-based Security (VBS) settings.
  Enabling Core Isolation uses virtualization to protect the system from attacks,
  while disabling it turns off this security feature.
actions:
  # Disable Core Isolation
  - !registryValue: {path: 'HKLM\SYSTEM\CurrentControlSet\Control\DeviceGuard', value: 'EnableVirtualizationBasedSecurity', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKLM\SYSTEM\CurrentControlSet\Control\DeviceGuard\Scenarios\HypervisorEnforcedCodeIntegrity', value: 'Enabled', type: REG_DWORD, data: '0'}