---
title: Optimized Browsers & Essential Components installation
description: >
  This section includes commands for installing popular web browsers (Brave, Firefox, Chrome) and optimizing them by disabling telemetry and unnecessary services. 
  It also installs essential components (.NET 3.5, DirectX, VCRedist) and adds browser extensions (uBlockOrigin).
actions: 
  # Install ViveTool
  - !writeStatus: {status: 'Installing ViveTool'}
  - !powerShell:
      command: '.\Install-Software.ps1 -MyArgument install_vivetool'
      runas: currentUserElevated
      exeDir: true
      wait: true
      weight: 100

  # Install Firefox
  - !writeStatus: {status: 'Installing Firefox', option: 'browser-firefox'}
  - !run: 
      exe: 'winget'
      args: 'install --id Mozilla.Firefox --silent --force --accept-source-agreements --accept-package-agreements'
      runas: currentUserElevated
      option: 'browser-firefox'
      showOutput: false
      wait: true
      weight: 100
  # Tweak Firefox
  - !powerShell:
      command: '& "RapidScripts\UtilityScripts\Browsers-Optimization.ps1" -MyArgument configure_firefox_policies, disable_firefox_updates'
      option: 'browser-firefox'
      exeDir: true
      weight: 100

  # Install Brave
  - !writeStatus: {status: 'Installing Brave', option: 'browser-brave'}
  - !run: 
      exe: 'winget'
      args: 'install --id Brave.Brave --silent --force --accept-source-agreements --accept-package-agreements'
      runas: currentUserElevated
      option: 'browser-brave'
      showOutput: false
      wait: true
      weight: 100

  # Install Thorium
  - !writeStatus: {status: 'Installing Thorium', option: 'browser-thorium'}
  - !run: 
      exe: 'winget'
      args: 'install --id Alex313031.Thorium --silent --force --accept-source-agreements'
      runas: currentUserElevated
      option: 'browser-thorium'
      showOutput: false
      wait: true
      weight: 100

  # Install Chrome
  - !writeStatus: {status: 'Installing Chrome', option: 'browser-chrome'}
  - !run: 
      exe: 'winget'
      args: 'install --id Google.Chrome --silent --force --accept-source-agreements --accept-package-agreements'
      runas: currentUserElevated
      option: 'browser-chrome'
      showOutput: false
      wait: true
      weight: 100
  # Install uBlockOrigin Lite
  - !powerShell:
      command: '& "RapidScripts\UtilityScripts\Browsers-Optimization.ps1" -MyArgument install_ublockorigin'
      option: 'browser-chrome'
      exeDir: true
      weight: 100

  # Install .NET 3.5
  - !writeStatus: {status: 'Installing .NET 3.5', option: 'install-dotnet'}
  - !powerShell:
      command: '.\Install-Software.ps1 -MyArgument install_dotnet'
      runas: system
      option: 'install-dotnet'
      exeDir: true
      wait: true
      weight: 100

  # Installing DirectX
  - !writeStatus: {status: 'Installing DirectX', option: 'install-directx'}
  - !run: 
      exe: 'winget'
      args: 'install --id Microsoft.DirectX --silent --force --accept-source-agreements --accept-package-agreements'
      runas: currentUserElevated
      option: 'install-directx'
      showOutput: false
      wait: true
      weight: 120

  # Installing VC++
  - !writeStatus: {status: 'Installing VC++', option: 'install-vcredist'}
  - !run: 
      exe: 'winget'
      args: 'install -e Microsoft.VCRedist.2005.x86 Microsoft.VCRedist.2005.x64 Microsoft.VCRedist.2008.x86 Microsoft.VCRedist.2008.x64 Microsoft.VCRedist.2010.x86 Microsoft.VCRedist.2010.x64 Microsoft.VCRedist.2012.x86 Microsoft.VCRedist.2012.x64 Microsoft.VCRedist.2013.x86 Microsoft.VCRedist.2013.x64 Microsoft.VCRedist.2015+.x86 Microsoft.VCRedist.2015+.x64 --silent --force --accept-source-agreements --accept-package-agreements'
      runas: currentUserElevated
      option: 'install-vcredist'
      showOutput: false
      wait: true
      weight: 150