---
title: Configure AppX Apps
description: >
  This script configures Windows AppX applications and system settings.
actions:
  # Reinstall Microsoft Store
  - !cmd: {command: 'wsreset -i', runas: currentUserElevated}

  # Disable Microsoft Store autoupdates
  - !task: {path: 'refinements\system\configure-microsoft-store.yml'}

  - !writeStatus: {status: 'Tweaking Edge', option: '!remove-msedge'}
  # Tweaking Edge
  - !taskKill: {name: 'MicrosoftEdgeUpdate', option: '!remove-msedge'}
  - !service: {name: 'MicrosoftEdgeElevationService', operation: change, startup: 4, option: '!remove-msedge'}
  - !service: {name: 'edgeupdate', operation: change, startup: 3, option: '!remove-msedge'}
  - !service: {name: 'edgeupdatem', operation: change, startup: 3, option: '!remove-msedge'}
  - !powerShell:
      command: '& "RapidScripts\UtilityScripts\Browsers-Optimization.ps1" -MyArgument configure_msedge_policies, disable_msedge_updates'
      option: '!remove-msedge'
      exeDir: true
      weight: 100